### ISSUE TITLE
Date filter for graphs only loads fully upon second button click. The space between x-axis values remains the same as the previous graph upon first click

### ISSUE THREAD

**Issue by michelle-x** [lizlinn/ourassignment#8]

**Comment by lizlinn** [comment]
Cannot resolve this issue. Users will have to click twice before the graph adjusts.

**Comment by michelle-x** [comment]
Attempted to move the "sleepChart.getData().clear();" statement around to see whether it affected the chart loading but it had no impact - the x-axis still lags after each filter.
